# Generated by CodiumAI
from app.calculator import Calculator

import pytest


class TestCalculator:
    # Tests that adding two positive numbers returns the correct result
    def test_add_positive_numbers(self):
        assert Calculator.add(2, 3) == 5

    # Tests that subtracting two positive numbers returns the correct result
    def test_subtract_positive_numbers(self):
        assert Calculator.subtract(5, 3) == 2

    # Tests that multiplying two positive numbers returns the correct result
    def test_multiply_positive_numbers(self):
        assert Calculator.multiply(2, 3) == 6

    # Tests that dividing two positive numbers returns the correct result
    def test_divide_positive_numbers(self):
        assert Calculator.divide(6, 3) == 2

    # Tests that adding a positive and a negative number returns the correct result
    def test_add_positive_and_negative_numbers(self):
        assert Calculator.add(2, -3) == -1

    # Tests that dividing a positive number by zero raises a ValueError
    def test_divide_positive_number_by_zero(self):
        with pytest.raises(ValueError):
            Calculator.divide(6, 0)

    # Tests that subtracting a positive and a negative number returns the correct result
    def test_subtract_positive_and_negative_numbers(self):
        assert Calculator.subtract(5, -3) == 8

    # Tests that multiplying a positive and a negative number returns the correct result
    def test_multiply_positive_and_negative_numbers(self):
        assert Calculator.multiply(2, -3) == -6

    # Tests that adding two negative numbers returns the correct result
    def test_add_negative_numbers(self):
        assert Calculator.add(-2, -3) == -5

    # Tests that subtracting two negative numbers returns the correct result
    def test_subtract_negative_numbers(self):
        assert Calculator.subtract(-5, -3) == -2

    # Tests that multiplying two negative numbers returns the correct result
    def test_multiply_negative_numbers(self):
        assert Calculator.multiply(-2, -3) == 6

    # Tests that dividing a negative number by a positive number returns the
    # correct result
    def test_divide_negative_by_positive(self):
        assert Calculator.divide(-10, 2) == -5

    # Tests that dividing a negative number by a negative number returns the
    # correct result
    def test_divide_negative_numbers(self):
        assert Calculator.divide(-10, -2) == 5
